//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupSettingV2) DeepCopyInto(out *GroupSettingV2) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupSettingV2.
func (in *GroupSettingV2) DeepCopy() *GroupSettingV2 {
	if in == nil {
		return nil
	}
	out := new(GroupSettingV2)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GroupSettingV2) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupSettingV2InitParameters) DeepCopyInto(out *GroupSettingV2InitParameters) {
	*out = *in
	if in.DescriptionAttribute != nil {
		in, out := &in.DescriptionAttribute, &out.DescriptionAttribute
		*out = new(string)
		**out = **in
	}
	if in.EnabledLdap != nil {
		in, out := &in.EnabledLdap, &out.EnabledLdap
		*out = new(string)
		**out = **in
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(string)
		**out = **in
	}
	if in.ForceAttributeSearch != nil {
		in, out := &in.ForceAttributeSearch, &out.ForceAttributeSearch
		*out = new(bool)
		**out = **in
	}
	if in.GroupBaseDn != nil {
		in, out := &in.GroupBaseDn, &out.GroupBaseDn
		*out = new(string)
		**out = **in
	}
	if in.GroupMemberAttribute != nil {
		in, out := &in.GroupMemberAttribute, &out.GroupMemberAttribute
		*out = new(string)
		**out = **in
	}
	if in.GroupNameAttribute != nil {
		in, out := &in.GroupNameAttribute, &out.GroupNameAttribute
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(string)
		**out = **in
	}
	if in.SubTree != nil {
		in, out := &in.SubTree, &out.SubTree
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupSettingV2InitParameters.
func (in *GroupSettingV2InitParameters) DeepCopy() *GroupSettingV2InitParameters {
	if in == nil {
		return nil
	}
	out := new(GroupSettingV2InitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupSettingV2List) DeepCopyInto(out *GroupSettingV2List) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GroupSettingV2, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupSettingV2List.
func (in *GroupSettingV2List) DeepCopy() *GroupSettingV2List {
	if in == nil {
		return nil
	}
	out := new(GroupSettingV2List)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GroupSettingV2List) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupSettingV2Observation) DeepCopyInto(out *GroupSettingV2Observation) {
	*out = *in
	if in.DescriptionAttribute != nil {
		in, out := &in.DescriptionAttribute, &out.DescriptionAttribute
		*out = new(string)
		**out = **in
	}
	if in.EnabledLdap != nil {
		in, out := &in.EnabledLdap, &out.EnabledLdap
		*out = new(string)
		**out = **in
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(string)
		**out = **in
	}
	if in.ForceAttributeSearch != nil {
		in, out := &in.ForceAttributeSearch, &out.ForceAttributeSearch
		*out = new(bool)
		**out = **in
	}
	if in.GroupBaseDn != nil {
		in, out := &in.GroupBaseDn, &out.GroupBaseDn
		*out = new(string)
		**out = **in
	}
	if in.GroupMemberAttribute != nil {
		in, out := &in.GroupMemberAttribute, &out.GroupMemberAttribute
		*out = new(string)
		**out = **in
	}
	if in.GroupNameAttribute != nil {
		in, out := &in.GroupNameAttribute, &out.GroupNameAttribute
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(string)
		**out = **in
	}
	if in.SubTree != nil {
		in, out := &in.SubTree, &out.SubTree
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupSettingV2Observation.
func (in *GroupSettingV2Observation) DeepCopy() *GroupSettingV2Observation {
	if in == nil {
		return nil
	}
	out := new(GroupSettingV2Observation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupSettingV2Parameters) DeepCopyInto(out *GroupSettingV2Parameters) {
	*out = *in
	if in.DescriptionAttribute != nil {
		in, out := &in.DescriptionAttribute, &out.DescriptionAttribute
		*out = new(string)
		**out = **in
	}
	if in.EnabledLdap != nil {
		in, out := &in.EnabledLdap, &out.EnabledLdap
		*out = new(string)
		**out = **in
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(string)
		**out = **in
	}
	if in.ForceAttributeSearch != nil {
		in, out := &in.ForceAttributeSearch, &out.ForceAttributeSearch
		*out = new(bool)
		**out = **in
	}
	if in.GroupBaseDn != nil {
		in, out := &in.GroupBaseDn, &out.GroupBaseDn
		*out = new(string)
		**out = **in
	}
	if in.GroupMemberAttribute != nil {
		in, out := &in.GroupMemberAttribute, &out.GroupMemberAttribute
		*out = new(string)
		**out = **in
	}
	if in.GroupNameAttribute != nil {
		in, out := &in.GroupNameAttribute, &out.GroupNameAttribute
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(string)
		**out = **in
	}
	if in.SubTree != nil {
		in, out := &in.SubTree, &out.SubTree
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupSettingV2Parameters.
func (in *GroupSettingV2Parameters) DeepCopy() *GroupSettingV2Parameters {
	if in == nil {
		return nil
	}
	out := new(GroupSettingV2Parameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupSettingV2Spec) DeepCopyInto(out *GroupSettingV2Spec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupSettingV2Spec.
func (in *GroupSettingV2Spec) DeepCopy() *GroupSettingV2Spec {
	if in == nil {
		return nil
	}
	out := new(GroupSettingV2Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupSettingV2Status) DeepCopyInto(out *GroupSettingV2Status) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupSettingV2Status.
func (in *GroupSettingV2Status) DeepCopy() *GroupSettingV2Status {
	if in == nil {
		return nil
	}
	out := new(GroupSettingV2Status)
	in.DeepCopyInto(out)
	return out
}
