apiVersion: remotegenericrepository.crossplane.io/v1alpha1
kind: GenericRepository
metadata:
  annotations:
    meta.upbound.io/example-id: remotegenericrepository/v1alpha1/genericrepository
  labels:
    testing.upbound.io/example-name: my-remote-generic
  name: my-remote-generic
spec:
  forProvider:
    key: my-remote-generic
    url: http://testartifactory.io/artifactory/example-generic/
