apiVersion: remote_huggingfaceml_repository.crossplane.io/v1alpha1
kind: HuggingfacemlRepository
metadata:
  annotations:
    meta.upbound.io/example-id: remote_huggingfaceml_repository/v1alpha1/huggingfacemlrepository
  labels:
    testing.upbound.io/example-name: huggingfaceml-remote
  name: huggingfaceml-remote
spec:
  forProvider:
    key: huggingfaceml-remote-foo25
