apiVersion: local_docker_v1_repository.crossplane.io/v1alpha1
kind: DockerV1Repository
metadata:
  annotations:
    meta.upbound.io/example-id: local_docker_v1_repository/v1alpha1/dockerv1repository
  labels:
    testing.upbound.io/example-name: foo
  name: foo
spec:
  forProvider:
    key: foo
