apiVersion: remotehelmrepository.crossplane.io/v1alpha1
kind: HelmRepository
metadata:
  annotations:
    meta.upbound.io/example-id: remotehelmrepository/v1alpha1/helmrepository
  labels:
    testing.upbound.io/example-name: helm-remote
  name: helm-remote
spec:
  forProvider:
    externalDependenciesEnabled: true
    externalDependenciesPatterns:
    - '**github.com**'
    helmChartsBaseUrl: https://foo.com
    key: helm-remote-foo25
    url: https://repo.chartcenter.io/
