apiVersion: local_repository_single_replication.crossplane.io/v1alpha1
kind: RepositorySingleReplication
metadata:
  annotations:
    meta.upbound.io/example-id: local_repository_single_replication/v1alpha1/repositorysinglereplication
  labels:
    testing.upbound.io/example-name: foo-rep
  name: foo-rep
spec:
  forProvider:
    checkBinaryExistenceInFilestore: true
    cronExp: 0 0 * * * ?
    enableEventReplication: true
    enabled: true
    excludePathPrefixPattern: /some-other-repo/
    includePathPrefixPattern: /some-repo/
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    repoKey: terraform-local-test-maven-repo-basic
    socketTimeoutMillis: 16000
    syncDeletes: false
    syncProperties: true
    syncStatistics: true
    url: ${var.artifactory_url}/artifactory/${artifactory_local_maven_repository.provider_test_dest.key}
    username: $var.artifactory_username

---

apiVersion: local_maven_repository.crossplane.io/v1alpha1
kind: MavenRepository
metadata:
  annotations:
    meta.upbound.io/example-id: local_repository_single_replication/v1alpha1/repositorysinglereplication
  labels:
    testing.upbound.io/example-name: provider_test_dest
  name: provider-test-dest
spec:
  forProvider:
    key: provider_test_dest

---

apiVersion: local_maven_repository.crossplane.io/v1alpha1
kind: MavenRepository
metadata:
  annotations:
    meta.upbound.io/example-id: local_repository_single_replication/v1alpha1/repositorysinglereplication
  labels:
    testing.upbound.io/example-name: provider_test_source
  name: provider-test-source
spec:
  forProvider:
    key: provider_test_source
