apiVersion: remote_npm_repository.crossplane.io/v1alpha1
kind: NpmRepository
metadata:
  annotations:
    meta.upbound.io/example-id: remote_npm_repository/v1alpha1/npmrepository
  labels:
    testing.upbound.io/example-name: npm-remote
  name: npm-remote
spec:
  forProvider:
    key: npm-remote
    listRemoteFolderItems: true
    mismatchingMimeTypesOverrideList: application/json,application/xml
    url: https://registry.npmjs.org
