apiVersion: dockerwebhook.crossplane.io/v1alpha1
kind: Webhook
metadata:
  annotations:
    meta.upbound.io/example-id: dockerwebhook/v1alpha1/webhook
  labels:
    testing.upbound.io/example-name: docker-webhook
  name: docker-webhook
spec:
  forProvider:
    criteria:
      - any_federated: false
        anyLocal: true
        anyRemote: false
        excludePatterns:
          - bar/**
        includePatterns:
          - foo/**
        repoKeys:
          - ${artifactory_local_docker_v2_repository.my-docker-local.key}
    eventTypes:
      - pushed
      - deleted
      - promoted
    handler:
      - customHttpHeaders:
          header-1: value-1
          header-2: value-2
        proxy: proxy-key
        secret: some-secret
        url: http://tempurl.org/webhook
    key: docker-webhook

---

apiVersion: localdockerv2repository.crossplane.io/v1alpha1
kind: DockerV2Repository
metadata:
  annotations:
    meta.upbound.io/example-id: dockerwebhook/v1alpha1/webhook
  labels:
    testing.upbound.io/example-name: my-docker-local
  name: my-docker-local
spec:
  forProvider:
    key: my-docker-local
