apiVersion: remote_chef_repository.crossplane.io/v1alpha1
kind: ChefRepository
metadata:
  annotations:
    meta.upbound.io/example-id: remote_chef_repository/v1alpha1/chefrepository
  labels:
    testing.upbound.io/example-name: my-remote-chef
  name: my-remote-chef
spec:
  forProvider:
    key: my-remote-chef
    url: https://supermarket.chef.io
