apiVersion: backup.crossplane.io/v1alpha1
kind: Backup
metadata:
  annotations:
    meta.upbound.io/example-id: backup/v1alpha1/backup
  labels:
    testing.upbound.io/example-name: backup_config_name
  name: backup-config-name
spec:
  forProvider:
    createArchive: false
    cronExp: 0 0 12 * * ? *
    enabled: true
    excludeNewRepositories: true
    excludedRepositories: []
    exportMissionControl: true
    key: backup_config_name
    retentionPeriodHours: 1000
    sendMailOnError: true
    verifyDiskSpace: true
