apiVersion: unmanageduser.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: unmanageduser/v1alpha1/user
  labels:
    testing.upbound.io/example-name: test-user
  name: test-user
spec:
  forProvider:
    email: test-user@artifactory-terraform.com
    groups:
    - logged-in-users
    name: terraform
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
