apiVersion: remotevcsrepository.crossplane.io/v1alpha1
kind: VcsRepository
metadata:
  annotations:
    meta.upbound.io/example-id: remotevcsrepository/v1alpha1/vcsrepository
  labels:
    testing.upbound.io/example-name: my-remote-vcs
  name: my-remote-vcs
spec:
  forProvider:
    key: my-remote-vcs
    maxUniqueSnapshots: 5
    url: https://github.com/
    vcsGitProvider: GITHUB
