apiVersion: dockercustomwebhook.crossplane.io/v1alpha1
kind: CustomWebhook
metadata:
  annotations:
    meta.upbound.io/example-id: dockercustomwebhook/v1alpha1/customwebhook
  labels:
    testing.upbound.io/example-name: docker-custom-webhook
  name: docker-custom-webhook
spec:
  forProvider:
    criteria:
      - anyLocal: true
        anyRemote: false
        excludePatterns:
          - bar/**
        includePatterns:
          - foo/**
        repoKeys:
          - ${artifactory_local_docker_v2_repository.my-docker-local.key}
    eventTypes:
      - pushed
      - deleted
      - promoted
    handler:
      - httpHeaders:
          headerName1: value1
          headerName2: value2
        payload: '{ "ref": "main" , "inputs": { "artifact_path": "test-repo/repo-path"
        } }'
        secrets:
          secretName1: value1
          secretName2: value2
        url: https://tempurl.org
    key: docker-custom_webhook

---

apiVersion: localdockerv2repository.crossplane.io/v1alpha1
kind: DockerV2Repository
metadata:
  annotations:
    meta.upbound.io/example-id: dockercustomwebhook/v1alpha1/customwebhook
  labels:
    testing.upbound.io/example-name: my-docker-local
  name: my-docker-local
spec:
  forProvider:
    key: my-docker-local
