//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingV2) DeepCopyInto(out *SettingV2) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingV2.
func (in *SettingV2) DeepCopy() *SettingV2 {
	if in == nil {
		return nil
	}
	out := new(SettingV2)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SettingV2) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingV2InitParameters) DeepCopyInto(out *SettingV2InitParameters) {
	*out = *in
	if in.AllowUserToAccessProfile != nil {
		in, out := &in.AllowUserToAccessProfile, &out.AllowUserToAccessProfile
		*out = new(bool)
		**out = **in
	}
	if in.AutoCreateUser != nil {
		in, out := &in.AutoCreateUser, &out.AutoCreateUser
		*out = new(bool)
		**out = **in
	}
	if in.EmailAttribute != nil {
		in, out := &in.EmailAttribute, &out.EmailAttribute
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.LdapPoisoningProtection != nil {
		in, out := &in.LdapPoisoningProtection, &out.LdapPoisoningProtection
		*out = new(bool)
		**out = **in
	}
	if in.LdapURL != nil {
		in, out := &in.LdapURL, &out.LdapURL
		*out = new(string)
		**out = **in
	}
	if in.ManagerDn != nil {
		in, out := &in.ManagerDn, &out.ManagerDn
		*out = new(string)
		**out = **in
	}
	if in.ManagerPasswordSecretRef != nil {
		in, out := &in.ManagerPasswordSecretRef, &out.ManagerPasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.PagingSupportEnabled != nil {
		in, out := &in.PagingSupportEnabled, &out.PagingSupportEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SearchBase != nil {
		in, out := &in.SearchBase, &out.SearchBase
		*out = new(string)
		**out = **in
	}
	if in.SearchFilter != nil {
		in, out := &in.SearchFilter, &out.SearchFilter
		*out = new(string)
		**out = **in
	}
	if in.SearchSubTree != nil {
		in, out := &in.SearchSubTree, &out.SearchSubTree
		*out = new(bool)
		**out = **in
	}
	if in.UserDnPattern != nil {
		in, out := &in.UserDnPattern, &out.UserDnPattern
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingV2InitParameters.
func (in *SettingV2InitParameters) DeepCopy() *SettingV2InitParameters {
	if in == nil {
		return nil
	}
	out := new(SettingV2InitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingV2List) DeepCopyInto(out *SettingV2List) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SettingV2, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingV2List.
func (in *SettingV2List) DeepCopy() *SettingV2List {
	if in == nil {
		return nil
	}
	out := new(SettingV2List)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SettingV2List) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingV2Observation) DeepCopyInto(out *SettingV2Observation) {
	*out = *in
	if in.AllowUserToAccessProfile != nil {
		in, out := &in.AllowUserToAccessProfile, &out.AllowUserToAccessProfile
		*out = new(bool)
		**out = **in
	}
	if in.AutoCreateUser != nil {
		in, out := &in.AutoCreateUser, &out.AutoCreateUser
		*out = new(bool)
		**out = **in
	}
	if in.EmailAttribute != nil {
		in, out := &in.EmailAttribute, &out.EmailAttribute
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.LdapPoisoningProtection != nil {
		in, out := &in.LdapPoisoningProtection, &out.LdapPoisoningProtection
		*out = new(bool)
		**out = **in
	}
	if in.LdapURL != nil {
		in, out := &in.LdapURL, &out.LdapURL
		*out = new(string)
		**out = **in
	}
	if in.ManagerDn != nil {
		in, out := &in.ManagerDn, &out.ManagerDn
		*out = new(string)
		**out = **in
	}
	if in.PagingSupportEnabled != nil {
		in, out := &in.PagingSupportEnabled, &out.PagingSupportEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SearchBase != nil {
		in, out := &in.SearchBase, &out.SearchBase
		*out = new(string)
		**out = **in
	}
	if in.SearchFilter != nil {
		in, out := &in.SearchFilter, &out.SearchFilter
		*out = new(string)
		**out = **in
	}
	if in.SearchSubTree != nil {
		in, out := &in.SearchSubTree, &out.SearchSubTree
		*out = new(bool)
		**out = **in
	}
	if in.UserDnPattern != nil {
		in, out := &in.UserDnPattern, &out.UserDnPattern
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingV2Observation.
func (in *SettingV2Observation) DeepCopy() *SettingV2Observation {
	if in == nil {
		return nil
	}
	out := new(SettingV2Observation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingV2Parameters) DeepCopyInto(out *SettingV2Parameters) {
	*out = *in
	if in.AllowUserToAccessProfile != nil {
		in, out := &in.AllowUserToAccessProfile, &out.AllowUserToAccessProfile
		*out = new(bool)
		**out = **in
	}
	if in.AutoCreateUser != nil {
		in, out := &in.AutoCreateUser, &out.AutoCreateUser
		*out = new(bool)
		**out = **in
	}
	if in.EmailAttribute != nil {
		in, out := &in.EmailAttribute, &out.EmailAttribute
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.LdapPoisoningProtection != nil {
		in, out := &in.LdapPoisoningProtection, &out.LdapPoisoningProtection
		*out = new(bool)
		**out = **in
	}
	if in.LdapURL != nil {
		in, out := &in.LdapURL, &out.LdapURL
		*out = new(string)
		**out = **in
	}
	if in.ManagerDn != nil {
		in, out := &in.ManagerDn, &out.ManagerDn
		*out = new(string)
		**out = **in
	}
	if in.ManagerPasswordSecretRef != nil {
		in, out := &in.ManagerPasswordSecretRef, &out.ManagerPasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.PagingSupportEnabled != nil {
		in, out := &in.PagingSupportEnabled, &out.PagingSupportEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SearchBase != nil {
		in, out := &in.SearchBase, &out.SearchBase
		*out = new(string)
		**out = **in
	}
	if in.SearchFilter != nil {
		in, out := &in.SearchFilter, &out.SearchFilter
		*out = new(string)
		**out = **in
	}
	if in.SearchSubTree != nil {
		in, out := &in.SearchSubTree, &out.SearchSubTree
		*out = new(bool)
		**out = **in
	}
	if in.UserDnPattern != nil {
		in, out := &in.UserDnPattern, &out.UserDnPattern
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingV2Parameters.
func (in *SettingV2Parameters) DeepCopy() *SettingV2Parameters {
	if in == nil {
		return nil
	}
	out := new(SettingV2Parameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingV2Spec) DeepCopyInto(out *SettingV2Spec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingV2Spec.
func (in *SettingV2Spec) DeepCopy() *SettingV2Spec {
	if in == nil {
		return nil
	}
	out := new(SettingV2Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingV2Status) DeepCopyInto(out *SettingV2Status) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingV2Status.
func (in *SettingV2Status) DeepCopy() *SettingV2Status {
	if in == nil {
		return nil
	}
	out := new(SettingV2Status)
	in.DeepCopyInto(out)
	return out
}
