apiVersion: virtualrpmrepository.crossplane.io/v1alpha1
kind: RpmRepository
metadata:
  annotations:
    meta.upbound.io/example-id: virtualrpmrepository/v1alpha1/rpmrepository
  labels:
    testing.upbound.io/example-name: foo-rpm-virtual
  name: foo-rpm-virtual
spec:
  forProvider:
    key: foo-rpm-virtual
    primaryKeypairRef: ${artifactory_keypair.primary-keypair.pair_name}
    secondaryKeypairRef: ${artifactory_keypair.secondary-keypair.pair_name}

---

apiVersion: keypair.crossplane.io/v1alpha1
kind: Keypair
metadata:
  annotations:
    meta.upbound.io/example-id: virtualrpmrepository/v1alpha1/rpmrepository
  labels:
    testing.upbound.io/example-name: primary-keypair
  name: primary-keypair
spec:
  forProvider:
    alias: foo-alias-1
    pairName: primary-keypair
    pairType: GPG
    privateKeySecretRef:
      key: attribute.gpg.priv
      name: example-secret
      namespace: upbound-system
    publicKey: ${file("samples/gpg.pub")}

---

apiVersion: keypair.crossplane.io/v1alpha1
kind: Keypair
metadata:
  annotations:
    meta.upbound.io/example-id: virtualrpmrepository/v1alpha1/rpmrepository
  labels:
    testing.upbound.io/example-name: secondary-keypair
  name: secondary-keypair
spec:
  forProvider:
    alias: foo-alias-2
    pairName: secondary-keypair
    pairType: GPG
    privateKeySecretRef:
      key: attribute.gpg.priv
      name: example-secret
      namespace: upbound-system
    publicKey: ${file("samples/gpg.pub")}
