apiVersion: federated_chef_repository.crossplane.io/v1alpha1
kind: ChefRepository
metadata:
  annotations:
    meta.upbound.io/example-id: federated_chef_repository/v1alpha1/chefrepository
  labels:
    testing.upbound.io/example-name: terraform-federated-test-chef-repo
  name: terraform-federated-test-chef-repo
spec:
  forProvider:
    key: terraform-federated-test-chef-repo
    member:
    - enabled: true
      url: http://tempurl.org/artifactory/terraform-federated-test-chef-repo
    - enabled: true
      url: http://tempurl2.org/artifactory/terraform-federated-test-chef-repo-2
