apiVersion: localswiftrepository.crossplane.io/v1alpha1
kind: SwiftRepository
metadata:
  annotations:
    meta.upbound.io/example-id: localswiftrepository/v1alpha1/swiftrepository
  labels:
    testing.upbound.io/example-name: terraform-local-test-swift-repo
  name: terraform-local-test-swift-repo
spec:
  forProvider:
    key: terraform-local-test-swift-repo
