/*
Copyright 2021 Upbound Inc.
*/

package config

import (
	// Note(turkenh): we are importing this to embed provider schema document
	_ "embed"
	"github.com/upbound/provider-artifactory/config/artifact_custom_webhook"
	"github.com/upbound/provider-artifactory/config/artifact_property_custom_webhook"
	"github.com/upbound/provider-artifactory/config/artifact_property_webhook"
	"github.com/upbound/provider-artifactory/config/artifact_webhook"
	"github.com/upbound/provider-artifactory/config/backup"
	"github.com/upbound/provider-artifactory/config/build_custom_webhook"
	"github.com/upbound/provider-artifactory/config/build_webhook"
	"github.com/upbound/provider-artifactory/config/certificate"
	"github.com/upbound/provider-artifactory/config/distribution_custom_webhook"
	"github.com/upbound/provider-artifactory/config/distribution_public_key"
	"github.com/upbound/provider-artifactory/config/distribution_webhook"
	"github.com/upbound/provider-artifactory/config/docker_custom_webhook"
	"github.com/upbound/provider-artifactory/config/docker_webhook"
	"github.com/upbound/provider-artifactory/config/federated_alpine_repository"
	"github.com/upbound/provider-artifactory/config/federated_bower_repository"
	"github.com/upbound/provider-artifactory/config/federated_cargo_repository"
	"github.com/upbound/provider-artifactory/config/federated_chef_repository"
	"github.com/upbound/provider-artifactory/config/federated_cocoapods_repository"
	"github.com/upbound/provider-artifactory/config/federated_composer_repository"
	"github.com/upbound/provider-artifactory/config/federated_conan_repository"
	"github.com/upbound/provider-artifactory/config/federated_conda_repository"
	"github.com/upbound/provider-artifactory/config/federated_cran_repository"
	"github.com/upbound/provider-artifactory/config/federated_debian_repository"
	"github.com/upbound/provider-artifactory/config/federated_docker_repository"
	"github.com/upbound/provider-artifactory/config/federated_docker_v1_repository"
	"github.com/upbound/provider-artifactory/config/federated_docker_v2_repository"
	"github.com/upbound/provider-artifactory/config/federated_gems_repository"
	"github.com/upbound/provider-artifactory/config/federated_generic_repository"
	"github.com/upbound/provider-artifactory/config/federated_gitlfs_repository"
	"github.com/upbound/provider-artifactory/config/federated_go_repository"
	"github.com/upbound/provider-artifactory/config/federated_gradle_repository"
	"github.com/upbound/provider-artifactory/config/federated_helm_repository"
	"github.com/upbound/provider-artifactory/config/federated_ivy_repository"
	"github.com/upbound/provider-artifactory/config/federated_maven_repository"
	"github.com/upbound/provider-artifactory/config/federated_npm_repository"
	"github.com/upbound/provider-artifactory/config/federated_nuget_repository"
	"github.com/upbound/provider-artifactory/config/federated_opkg_repository"
	"github.com/upbound/provider-artifactory/config/federated_puppet_repository"
	"github.com/upbound/provider-artifactory/config/federated_pypi_repository"
	"github.com/upbound/provider-artifactory/config/federated_rpm_repository"
	"github.com/upbound/provider-artifactory/config/federated_sbt_repository"
	"github.com/upbound/provider-artifactory/config/federated_swift_repository"
	"github.com/upbound/provider-artifactory/config/federated_terraform_module_repository"
	"github.com/upbound/provider-artifactory/config/federated_terraform_provider_repository"
	"github.com/upbound/provider-artifactory/config/federated_vagrant_repository"
	"github.com/upbound/provider-artifactory/config/general_security"
	"github.com/upbound/provider-artifactory/config/global_environment"
	"github.com/upbound/provider-artifactory/config/group"
	"github.com/upbound/provider-artifactory/config/keypair"
	"github.com/upbound/provider-artifactory/config/ldap_group_setting"
	"github.com/upbound/provider-artifactory/config/ldap_group_setting_v2"
	"github.com/upbound/provider-artifactory/config/ldap_setting"
	"github.com/upbound/provider-artifactory/config/ldap_setting_v2"
	"github.com/upbound/provider-artifactory/config/local_alpine_repository"
	"github.com/upbound/provider-artifactory/config/local_bower_repository"
	"github.com/upbound/provider-artifactory/config/local_cargo_repository"
	"github.com/upbound/provider-artifactory/config/local_chef_repository"
	"github.com/upbound/provider-artifactory/config/local_cocoapods_repository"
	"github.com/upbound/provider-artifactory/config/local_composer_repository"
	"github.com/upbound/provider-artifactory/config/local_conan_repository"
	"github.com/upbound/provider-artifactory/config/local_conda_repository"
	"github.com/upbound/provider-artifactory/config/local_cran_repository"
	"github.com/upbound/provider-artifactory/config/local_debian_repository"
	"github.com/upbound/provider-artifactory/config/local_docker_v1_repository"
	"github.com/upbound/provider-artifactory/config/local_docker_v2_repository"
	"github.com/upbound/provider-artifactory/config/local_gems_repository"
	"github.com/upbound/provider-artifactory/config/local_generic_repository"
	"github.com/upbound/provider-artifactory/config/local_gitlfs_repository"
	"github.com/upbound/provider-artifactory/config/local_go_repository"
	"github.com/upbound/provider-artifactory/config/local_gradle_repository"
	"github.com/upbound/provider-artifactory/config/local_helm_repository"
	"github.com/upbound/provider-artifactory/config/local_huggingfaceml_repository"
	"github.com/upbound/provider-artifactory/config/local_ivy_repository"
	"github.com/upbound/provider-artifactory/config/local_maven_repository"
	"github.com/upbound/provider-artifactory/config/local_npm_repository"
	"github.com/upbound/provider-artifactory/config/local_nuget_repository"
	"github.com/upbound/provider-artifactory/config/local_oci_repository"
	"github.com/upbound/provider-artifactory/config/local_opkg_repository"
	"github.com/upbound/provider-artifactory/config/local_pub_repository"
	"github.com/upbound/provider-artifactory/config/local_puppet_repository"
	"github.com/upbound/provider-artifactory/config/local_pypi_repository"
	"github.com/upbound/provider-artifactory/config/local_repository_multi_replication"
	"github.com/upbound/provider-artifactory/config/local_repository_single_replication"
	"github.com/upbound/provider-artifactory/config/local_rpm_repository"
	"github.com/upbound/provider-artifactory/config/local_sbt_repository"
	"github.com/upbound/provider-artifactory/config/local_swift_repository"
	"github.com/upbound/provider-artifactory/config/local_terraform_module_repository"
	"github.com/upbound/provider-artifactory/config/local_terraform_provider_repository"
	"github.com/upbound/provider-artifactory/config/local_terraformbackend_repository"
	"github.com/upbound/provider-artifactory/config/local_vagrant_repository"
	"github.com/upbound/provider-artifactory/config/mail_server"
	"github.com/upbound/provider-artifactory/config/managed_user"
	"github.com/upbound/provider-artifactory/config/oauth_settings"
	"github.com/upbound/provider-artifactory/config/package_cleanup_policy"
	"github.com/upbound/provider-artifactory/config/password_expiration_policy"
	"github.com/upbound/provider-artifactory/config/property_set"
	"github.com/upbound/provider-artifactory/config/proxy"
	"github.com/upbound/provider-artifactory/config/release_bundle_custom_webhook"
	"github.com/upbound/provider-artifactory/config/release_bundle_v2"
	"github.com/upbound/provider-artifactory/config/release_bundle_v2_custom_webhook"
	"github.com/upbound/provider-artifactory/config/release_bundle_v2_promotion"
	"github.com/upbound/provider-artifactory/config/release_bundle_v2_promotion_custom_webhook"
	"github.com/upbound/provider-artifactory/config/release_bundle_v2_promotion_webhook"
	"github.com/upbound/provider-artifactory/config/release_bundle_v2_webhook"
	"github.com/upbound/provider-artifactory/config/release_bundle_webhook"
	"github.com/upbound/provider-artifactory/config/remote_alpine_repository"
	"github.com/upbound/provider-artifactory/config/remote_bower_repository"
	"github.com/upbound/provider-artifactory/config/remote_cargo_repository"
	"github.com/upbound/provider-artifactory/config/remote_chef_repository"
	"github.com/upbound/provider-artifactory/config/remote_cocoapods_repository"
	"github.com/upbound/provider-artifactory/config/remote_composer_repository"
	"github.com/upbound/provider-artifactory/config/remote_conan_repository"
	"github.com/upbound/provider-artifactory/config/remote_conda_repository"
	"github.com/upbound/provider-artifactory/config/remote_cran_repository"
	"github.com/upbound/provider-artifactory/config/remote_debian_repository"
	"github.com/upbound/provider-artifactory/config/remote_docker_repository"
	"github.com/upbound/provider-artifactory/config/remote_gems_repository"
	"github.com/upbound/provider-artifactory/config/remote_generic_repository"
	"github.com/upbound/provider-artifactory/config/remote_gitlfs_repository"
	"github.com/upbound/provider-artifactory/config/remote_go_repository"
	"github.com/upbound/provider-artifactory/config/remote_gradle_repository"
	"github.com/upbound/provider-artifactory/config/remote_helm_repository"
	"github.com/upbound/provider-artifactory/config/remote_huggingfaceml_repository"
	"github.com/upbound/provider-artifactory/config/remote_ivy_repository"
	"github.com/upbound/provider-artifactory/config/remote_maven_repository"
	"github.com/upbound/provider-artifactory/config/remote_npm_repository"
	"github.com/upbound/provider-artifactory/config/remote_nuget_repository"
	"github.com/upbound/provider-artifactory/config/remote_oci_repository"
	"github.com/upbound/provider-artifactory/config/remote_opkg_repository"
	"github.com/upbound/provider-artifactory/config/remote_p2_repository"
	"github.com/upbound/provider-artifactory/config/remote_pub_repository"
	"github.com/upbound/provider-artifactory/config/remote_puppet_repository"
	"github.com/upbound/provider-artifactory/config/remote_pypi_repository"
	"github.com/upbound/provider-artifactory/config/remote_repository_replication"
	"github.com/upbound/provider-artifactory/config/remote_rpm_repository"
	"github.com/upbound/provider-artifactory/config/remote_sbt_repository"
	"github.com/upbound/provider-artifactory/config/remote_swift_repository"
	"github.com/upbound/provider-artifactory/config/remote_terraform_repository"
	"github.com/upbound/provider-artifactory/config/remote_vcs_repository"
	"github.com/upbound/provider-artifactory/config/repository_layout"
	"github.com/upbound/provider-artifactory/config/scoped_token"
	"github.com/upbound/provider-artifactory/config/unmanaged_user"
	"github.com/upbound/provider-artifactory/config/user"
	"github.com/upbound/provider-artifactory/config/user_custom_webhook"
	"github.com/upbound/provider-artifactory/config/user_lock_policy"
	"github.com/upbound/provider-artifactory/config/user_webhook"
	"github.com/upbound/provider-artifactory/config/virtual_alpine_repository"
	"github.com/upbound/provider-artifactory/config/virtual_bower_repository"
	"github.com/upbound/provider-artifactory/config/virtual_chef_repository"
	"github.com/upbound/provider-artifactory/config/virtual_cocoapods_repository"
	"github.com/upbound/provider-artifactory/config/virtual_composer_repository"
	"github.com/upbound/provider-artifactory/config/virtual_conan_repository"
	"github.com/upbound/provider-artifactory/config/virtual_conda_repository"
	"github.com/upbound/provider-artifactory/config/virtual_cran_repository"
	"github.com/upbound/provider-artifactory/config/virtual_debian_repository"
	"github.com/upbound/provider-artifactory/config/virtual_docker_repository"
	"github.com/upbound/provider-artifactory/config/virtual_gems_repository"
	"github.com/upbound/provider-artifactory/config/virtual_generic_repository"
	"github.com/upbound/provider-artifactory/config/virtual_gitlfs_repository"
	"github.com/upbound/provider-artifactory/config/virtual_go_repository"
	"github.com/upbound/provider-artifactory/config/virtual_gradle_repository"
	"github.com/upbound/provider-artifactory/config/virtual_helm_repository"
	"github.com/upbound/provider-artifactory/config/virtual_ivy_repository"
	"github.com/upbound/provider-artifactory/config/virtual_maven_repository"
	"github.com/upbound/provider-artifactory/config/virtual_npm_repository"
	"github.com/upbound/provider-artifactory/config/virtual_nuget_repository"
	"github.com/upbound/provider-artifactory/config/virtual_oci_repository"
	"github.com/upbound/provider-artifactory/config/virtual_opkg_repository"
	"github.com/upbound/provider-artifactory/config/virtual_p2_repository"
	"github.com/upbound/provider-artifactory/config/virtual_pub_repository"
	"github.com/upbound/provider-artifactory/config/virtual_puppet_repository"
	"github.com/upbound/provider-artifactory/config/virtual_pypi_repository"
	"github.com/upbound/provider-artifactory/config/virtual_rpm_repository"
	"github.com/upbound/provider-artifactory/config/virtual_sbt_repository"
	"github.com/upbound/provider-artifactory/config/virtual_swift_repository"
	"github.com/upbound/provider-artifactory/config/virtual_terraform_repository"

	ujconfig "github.com/crossplane/upjet/pkg/config"
)

const (
	resourcePrefix = "artifactory"
	modulePath     = "github.com/upbound/provider-artifactory"
)

//go:embed schema.json
var providerSchema string

//go:embed provider-metadata.yaml
var providerMetadata string

// GetProvider returns provider configuration
func GetProvider() *ujconfig.Provider {
	pc := ujconfig.NewProvider([]byte(providerSchema), resourcePrefix, modulePath, []byte(providerMetadata),
		ujconfig.WithRootGroup("crossplane.io"),
		ujconfig.WithIncludeList(ExternalNameConfigured()),
		ujconfig.WithFeaturesPackage("internal/features"),
		ujconfig.WithDefaultResourceOptions(
			ExternalNameConfigurations(),
		))

	for _, configure := range []func(provider *ujconfig.Provider){
		// add custom config functions
		backup.Configure,
		general_security.Configure,
		ldap_group_setting.Configure,
		ldap_group_setting_v2.Configure,
		ldap_setting.Configure,
		ldap_setting_v2.Configure,
		mail_server.Configure,
		oauth_settings.Configure,
		package_cleanup_policy.Configure,
		property_set.Configure,
		proxy.Configure,
		repository_layout.Configure,
		federated_alpine_repository.Configure,
		federated_bower_repository.Configure,
		federated_cargo_repository.Configure,
		federated_chef_repository.Configure,
		federated_cocoapods_repository.Configure,
		federated_composer_repository.Configure,
		federated_conan_repository.Configure,
		federated_conda_repository.Configure,
		federated_cran_repository.Configure,
		federated_debian_repository.Configure,
		federated_docker_repository.Configure,
		federated_docker_v1_repository.Configure,
		federated_docker_v2_repository.Configure,
		federated_gems_repository.Configure,
		federated_generic_repository.Configure,
		federated_gitlfs_repository.Configure,
		federated_go_repository.Configure,
		federated_gradle_repository.Configure,
		federated_helm_repository.Configure,
		federated_ivy_repository.Configure,
		federated_maven_repository.Configure,
		federated_npm_repository.Configure,
		federated_nuget_repository.Configure,
		federated_opkg_repository.Configure,
		federated_puppet_repository.Configure,
		federated_pypi_repository.Configure,
		federated_rpm_repository.Configure,
		federated_sbt_repository.Configure,
		federated_swift_repository.Configure,
		federated_terraform_module_repository.Configure,
		federated_terraform_provider_repository.Configure,
		federated_vagrant_repository.Configure,
		release_bundle_v2.Configure,
		release_bundle_v2_promotion.Configure,
		local_alpine_repository.Configure,
		local_bower_repository.Configure,
		local_cargo_repository.Configure,
		local_chef_repository.Configure,
		local_cocoapods_repository.Configure,
		local_composer_repository.Configure,
		local_conan_repository.Configure,
		local_conda_repository.Configure,
		local_cran_repository.Configure,
		local_debian_repository.Configure,
		local_docker_v1_repository.Configure,
		local_docker_v2_repository.Configure,
		local_gems_repository.Configure,
		local_generic_repository.Configure,
		local_gitlfs_repository.Configure,
		local_go_repository.Configure,
		local_gradle_repository.Configure,
		local_helm_repository.Configure,
		local_huggingfaceml_repository.Configure,
		local_ivy_repository.Configure,
		local_maven_repository.Configure,
		local_npm_repository.Configure,
		local_nuget_repository.Configure,
		local_oci_repository.Configure,
		local_opkg_repository.Configure,
		local_pub_repository.Configure,
		local_puppet_repository.Configure,
		local_pypi_repository.Configure,
		local_rpm_repository.Configure,
		local_sbt_repository.Configure,
		local_swift_repository.Configure,
		local_terraform_module_repository.Configure,
		local_terraform_provider_repository.Configure,
		local_terraformbackend_repository.Configure,
		local_vagrant_repository.Configure,
		remote_alpine_repository.Configure,
		remote_bower_repository.Configure,
		remote_cargo_repository.Configure,
		remote_chef_repository.Configure,
		remote_cocoapods_repository.Configure,
		remote_composer_repository.Configure,
		remote_conan_repository.Configure,
		remote_conda_repository.Configure,
		remote_cran_repository.Configure,
		remote_debian_repository.Configure,
		remote_docker_repository.Configure,
		remote_gems_repository.Configure,
		remote_generic_repository.Configure,
		remote_gitlfs_repository.Configure,
		remote_go_repository.Configure,
		remote_gradle_repository.Configure,
		remote_helm_repository.Configure,
		remote_huggingfaceml_repository.Configure,
		remote_ivy_repository.Configure,
		remote_maven_repository.Configure,
		remote_npm_repository.Configure,
		remote_nuget_repository.Configure,
		remote_oci_repository.Configure,
		remote_opkg_repository.Configure,
		remote_p2_repository.Configure,
		remote_pub_repository.Configure,
		remote_puppet_repository.Configure,
		remote_pypi_repository.Configure,
		remote_rpm_repository.Configure,
		remote_sbt_repository.Configure,
		remote_swift_repository.Configure,
		remote_terraform_repository.Configure,
		remote_vcs_repository.Configure,
		local_repository_multi_replication.Configure,
		local_repository_single_replication.Configure,
		remote_repository_replication.Configure,
		certificate.Configure,
		distribution_public_key.Configure,
		global_environment.Configure,
		group.Configure,
		keypair.Configure,
		password_expiration_policy.Configure,
		scoped_token.Configure,
		user_lock_policy.Configure,
		managed_user.Configure,
		unmanaged_user.Configure,
		user.Configure,
		virtual_alpine_repository.Configure,
		virtual_bower_repository.Configure,
		virtual_chef_repository.Configure,
		virtual_cocoapods_repository.Configure,
		virtual_composer_repository.Configure,
		virtual_conan_repository.Configure,
		virtual_conda_repository.Configure,
		virtual_cran_repository.Configure,
		virtual_debian_repository.Configure,
		virtual_docker_repository.Configure,
		virtual_gems_repository.Configure,
		virtual_generic_repository.Configure,
		virtual_gitlfs_repository.Configure,
		virtual_go_repository.Configure,
		virtual_gradle_repository.Configure,
		virtual_helm_repository.Configure,
		virtual_ivy_repository.Configure,
		virtual_maven_repository.Configure,
		virtual_npm_repository.Configure,
		virtual_nuget_repository.Configure,
		virtual_oci_repository.Configure,
		virtual_opkg_repository.Configure,
		virtual_p2_repository.Configure,
		virtual_pub_repository.Configure,
		virtual_puppet_repository.Configure,
		virtual_pypi_repository.Configure,
		virtual_rpm_repository.Configure,
		virtual_sbt_repository.Configure,
		virtual_swift_repository.Configure,
		virtual_terraform_repository.Configure,
		artifact_custom_webhook.Configure,
		artifact_property_custom_webhook.Configure,
		artifact_property_webhook.Configure,
		artifact_webhook.Configure,
		release_bundle_custom_webhook.Configure,
		release_bundle_webhook.Configure,
		build_custom_webhook.Configure,
		build_webhook.Configure,
		distribution_custom_webhook.Configure,
		distribution_webhook.Configure,
		docker_custom_webhook.Configure,
		docker_webhook.Configure,
		release_bundle_v2_custom_webhook.Configure,
		release_bundle_v2_promotion_custom_webhook.Configure,
		release_bundle_v2_promotion_webhook.Configure,
		release_bundle_v2_webhook.Configure,
		user_custom_webhook.Configure,
		user_webhook.Configure,
	} {
		configure(pc)
	}

	pc.ConfigureResources()
	return pc
}
