apiVersion: federatedopkgrepository.crossplane.io/v1alpha1
kind: OpkgRepository
metadata:
  annotations:
    meta.upbound.io/example-id: federatedopkgrepository/v1alpha1/opkgrepository
  labels:
    testing.upbound.io/example-name: terraform-federated-test-opkg-repo
  name: terraform-federated-test-opkg-repo
spec:
  forProvider:
    key: terraform-federated-test-opkg-repo
    member:
    - enabled: true
      url: http://tempurl.org/artifactory/terraform-federated-test-opkg-repo
    - enabled: true
      url: http://tempurl2.org/artifactory/terraform-federated-test-opkg-repo-2
