apiVersion: distribution_webhook.crossplane.io/v1alpha1
kind: Webhook
metadata:
  annotations:
    meta.upbound.io/example-id: distribution_webhook/v1alpha1/webhook
  labels:
    testing.upbound.io/example-name: distribution-webhook
  name: distribution-webhook
spec:
  forProvider:
    criteria:
    - anyReleaseBundle: false
      excludePatterns:
      - bar/**
      includePatterns:
      - foo/**
      registeredReleaseBundleNames:
      - bundle-name
    eventTypes:
    - distribute_started
    - distribute_completed
    - distribute_aborted
    - distribute_failed
    - delete_started
    - delete_completed
    - delete_failed
    handler:
    - customHttpHeaders:
        header-1: value-1
        header-2: value-2
      proxy: proxy-key
      secret: some-secret
      url: http://tempurl.org/webhook
    key: distribution-webhook
