apiVersion: federatedcondarepository.crossplane.io/v1alpha1
kind: CondaRepository
metadata:
  annotations:
    meta.upbound.io/example-id: federatedcondarepository/v1alpha1/condarepository
  labels:
    testing.upbound.io/example-name: terraform-federated-test-conda-repo
  name: terraform-federated-test-conda-repo
spec:
  forProvider:
    key: terraform-federated-test-conda-repo
    member:
      - enabled: true
        url: http://tempurl.org/artifactory/terraform-federated-test-conda-repo
      - enabled: true
        url: http://tempurl2.org/artifactory/terraform-federated-test-conda-repo-2
