apiVersion: virtual_gradle_repository.crossplane.io/v1alpha1
kind: GradleRepository
metadata:
  annotations:
    meta.upbound.io/example-id: virtual_gradle_repository/v1alpha1/gradlerepository
  labels:
    testing.upbound.io/example-name: foo-gradle
  name: foo-gradle
spec:
  forProvider:
    description: A test virtual repo
    excludesPattern: com/google/**
    includesPattern: com/jfrog/**,cloud/jfrog/**
    key: foo-gradle
    notes: Internal description
    pomRepositoryReferencesCleanupPolicy: discard_active_reference
    repositories: []
