apiVersion: build_custom_webhook.crossplane.io/v1alpha1
kind: CustomWebhook
metadata:
  annotations:
    meta.upbound.io/example-id: build_custom_webhook/v1alpha1/customwebhook
  labels:
    testing.upbound.io/example-name: build-custom-webhook
  name: build-custom-webhook
spec:
  forProvider:
    criteria:
    - anyBuild: true
      excludePatterns:
      - bar/**
      includePatterns:
      - foo/**
      selectedBuilds:
      - build-id
    eventTypes:
    - uploaded
    - deleted
    - promoted
    handler:
    - httpHeaders:
        headerName1: value1
        headerName2: value2
      payload: '{ "ref": "main" , "inputs": { "artifact_path": "test-repo/repo-path"
        } }'
      secrets:
        secretName1: value1
        secretName2: value2
      url: https://tempurl.org
    key: build-custom-webhook
