apiVersion: anonymous.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: anonymous/v1alpha1/user
  labels:
    testing.upbound.io/example-name: anonymous
  name: anonymous
spec:
  forProvider: {}
