apiVersion: federated_npm_repository.crossplane.io/v1alpha1
kind: NpmRepository
metadata:
  annotations:
    meta.upbound.io/example-id: federated_npm_repository/v1alpha1/npmrepository
  labels:
    testing.upbound.io/example-name: terraform-federated-test-npm-repo
  name: terraform-federated-test-npm-repo
spec:
  forProvider:
    key: terraform-federated-test-npm-repo
    member:
    - enabled: true
      url: http://tempurl.org/artifactory/terraform-federated-test-npm-repo
    - enabled: true
      url: http://tempurl2.org/artifactory/terraform-federated-test-npm-repo-2
