// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type CriteriaInitParameters struct {

	// Trigger on any local repo.
	// Trigger on any local repositories
	AnyLocal *bool `json:"anyLocal,omitempty" tf:"any_local,omitempty"`

	// Trigger on any remote repo.
	// Trigger on any remote repositories
	AnyRemote *bool `json:"anyRemote,omitempty" tf:"any_remote,omitempty"`

	// Simple comma separated wildcard patterns for repository artifact paths (with no leading slash). Ant-style path expressions are supported (*, **, ?). For example: org/apache/**.
	// Simple comma separated wildcard patterns for repository artifact paths (with no leading slash).\nAnt-style path expressions are supported (*, **, ?).\nFor example: "org/apache/**"
	// +listType=set
	ExcludePatterns []*string `json:"excludePatterns,omitempty" tf:"exclude_patterns,omitempty"`

	// Simple comma separated wildcard patterns for repository artifact paths (with no leading slash). Ant-style path expressions are supported (*, **, ?). For example: org/apache/**.
	// Simple comma separated wildcard patterns for repository artifact paths (with no leading slash).\nAnt-style path expressions are supported (*, **, ?).\nFor example: "org/apache/**"
	// +listType=set
	IncludePatterns []*string `json:"includePatterns,omitempty" tf:"include_patterns,omitempty"`

	// Trigger on this list of repo keys.
	// Trigger on this list of repository keys
	// +listType=set
	RepoKeys []*string `json:"repoKeys,omitempty" tf:"repo_keys,omitempty"`
}

type CriteriaObservation struct {

	// Trigger on any local repo.
	// Trigger on any local repositories
	AnyLocal *bool `json:"anyLocal,omitempty" tf:"any_local,omitempty"`

	// Trigger on any remote repo.
	// Trigger on any remote repositories
	AnyRemote *bool `json:"anyRemote,omitempty" tf:"any_remote,omitempty"`

	// Simple comma separated wildcard patterns for repository artifact paths (with no leading slash). Ant-style path expressions are supported (*, **, ?). For example: org/apache/**.
	// Simple comma separated wildcard patterns for repository artifact paths (with no leading slash).\nAnt-style path expressions are supported (*, **, ?).\nFor example: "org/apache/**"
	// +listType=set
	ExcludePatterns []*string `json:"excludePatterns,omitempty" tf:"exclude_patterns,omitempty"`

	// Simple comma separated wildcard patterns for repository artifact paths (with no leading slash). Ant-style path expressions are supported (*, **, ?). For example: org/apache/**.
	// Simple comma separated wildcard patterns for repository artifact paths (with no leading slash).\nAnt-style path expressions are supported (*, **, ?).\nFor example: "org/apache/**"
	// +listType=set
	IncludePatterns []*string `json:"includePatterns,omitempty" tf:"include_patterns,omitempty"`

	// Trigger on this list of repo keys.
	// Trigger on this list of repository keys
	// +listType=set
	RepoKeys []*string `json:"repoKeys,omitempty" tf:"repo_keys,omitempty"`
}

type CriteriaParameters struct {

	// Trigger on any local repo.
	// Trigger on any local repositories
	// +kubebuilder:validation:Optional
	AnyLocal *bool `json:"anyLocal" tf:"any_local,omitempty"`

	// Trigger on any remote repo.
	// Trigger on any remote repositories
	// +kubebuilder:validation:Optional
	AnyRemote *bool `json:"anyRemote" tf:"any_remote,omitempty"`

	// Simple comma separated wildcard patterns for repository artifact paths (with no leading slash). Ant-style path expressions are supported (*, **, ?). For example: org/apache/**.
	// Simple comma separated wildcard patterns for repository artifact paths (with no leading slash).\nAnt-style path expressions are supported (*, **, ?).\nFor example: "org/apache/**"
	// +kubebuilder:validation:Optional
	// +listType=set
	ExcludePatterns []*string `json:"excludePatterns,omitempty" tf:"exclude_patterns,omitempty"`

	// Simple comma separated wildcard patterns for repository artifact paths (with no leading slash). Ant-style path expressions are supported (*, **, ?). For example: org/apache/**.
	// Simple comma separated wildcard patterns for repository artifact paths (with no leading slash).\nAnt-style path expressions are supported (*, **, ?).\nFor example: "org/apache/**"
	// +kubebuilder:validation:Optional
	// +listType=set
	IncludePatterns []*string `json:"includePatterns,omitempty" tf:"include_patterns,omitempty"`

	// Trigger on this list of repo keys.
	// Trigger on this list of repository keys
	// +kubebuilder:validation:Optional
	// +listType=set
	RepoKeys []*string `json:"repoKeys" tf:"repo_keys,omitempty"`
}

type CustomWebhookInitParameters struct {

	// Specifies where the webhook will be applied on which repositories.
	// Specifies where the webhook will be applied on which repositories.
	Criteria []CriteriaInitParameters `json:"criteria,omitempty" tf:"criteria,omitempty"`

	// Webhook description. Max length 1000 characters.
	// Description of webhook. Max length 1000 characters.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Status of webhook. Default to true.
	// Status of webhook. Default to 'true'
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// List of Events in Artifactory, Distribution, Release Bundle that function as the event trigger for the Webhook. Allow values: pushed, deleted, promoted.
	// List of Events in Artifactory, Distribution, Release Bundle that function as the event trigger for the Webhook.
	// Allow values: pushed, deleted, promoted
	// +listType=set
	EventTypes []*string `json:"eventTypes,omitempty" tf:"event_types,omitempty"`

	// At least one is required.
	Handler []HandlerInitParameters `json:"handler,omitempty" tf:"handler,omitempty"`

	// The identity key of the webhook. Must be between 2 and 200 characters. Cannot contain spaces.
	// Key of webhook. Must be between 2 and 200 characters. Cannot contain spaces.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`
}

type CustomWebhookObservation struct {

	// Specifies where the webhook will be applied on which repositories.
	// Specifies where the webhook will be applied on which repositories.
	Criteria []CriteriaObservation `json:"criteria,omitempty" tf:"criteria,omitempty"`

	// Webhook description. Max length 1000 characters.
	// Description of webhook. Max length 1000 characters.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Status of webhook. Default to true.
	// Status of webhook. Default to 'true'
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// List of Events in Artifactory, Distribution, Release Bundle that function as the event trigger for the Webhook. Allow values: pushed, deleted, promoted.
	// List of Events in Artifactory, Distribution, Release Bundle that function as the event trigger for the Webhook.
	// Allow values: pushed, deleted, promoted
	// +listType=set
	EventTypes []*string `json:"eventTypes,omitempty" tf:"event_types,omitempty"`

	// At least one is required.
	Handler []HandlerObservation `json:"handler,omitempty" tf:"handler,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The identity key of the webhook. Must be between 2 and 200 characters. Cannot contain spaces.
	// Key of webhook. Must be between 2 and 200 characters. Cannot contain spaces.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`
}

type CustomWebhookParameters struct {

	// Specifies where the webhook will be applied on which repositories.
	// Specifies where the webhook will be applied on which repositories.
	// +kubebuilder:validation:Optional
	Criteria []CriteriaParameters `json:"criteria,omitempty" tf:"criteria,omitempty"`

	// Webhook description. Max length 1000 characters.
	// Description of webhook. Max length 1000 characters.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Status of webhook. Default to true.
	// Status of webhook. Default to 'true'
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// List of Events in Artifactory, Distribution, Release Bundle that function as the event trigger for the Webhook. Allow values: pushed, deleted, promoted.
	// List of Events in Artifactory, Distribution, Release Bundle that function as the event trigger for the Webhook.
	// Allow values: pushed, deleted, promoted
	// +kubebuilder:validation:Optional
	// +listType=set
	EventTypes []*string `json:"eventTypes,omitempty" tf:"event_types,omitempty"`

	// At least one is required.
	// +kubebuilder:validation:Optional
	Handler []HandlerParameters `json:"handler,omitempty" tf:"handler,omitempty"`

	// The identity key of the webhook. Must be between 2 and 200 characters. Cannot contain spaces.
	// Key of webhook. Must be between 2 and 200 characters. Cannot contain spaces.
	// +kubebuilder:validation:Optional
	Key *string `json:"key,omitempty" tf:"key,omitempty"`
}

type HandlerInitParameters struct {

	// HTTP headers you wish to use to invoke the Webhook, comprise key/value pair.
	// HTTP headers you wish to use to invoke the Webhook, comprise of key/value pair. Used in custom webhooks.
	// +mapType=granular
	HTTPHeaders map[string]*string `json:"httpHeaders,omitempty" tf:"http_headers,omitempty"`

	// This attribute is used to build the request body. Used in custom webhooks
	Payload *string `json:"payload,omitempty" tf:"payload,omitempty"`

	// Proxy key from Artifactory UI (Administration -> Proxies -> Configuration).
	// Proxy key from Artifactory UI (Administration -> Proxies -> Configuration)
	Proxy *string `json:"proxy,omitempty" tf:"proxy,omitempty"`

	// Defines a set of sensitive values (such as, tokens and passwords) that can be injected in the headers and/or payload.Secrets’ values are encrypted. In the header/payload, the value can be invoked using the {{.secrets.token}} format, where token is the name provided for the secret value. Comprise key/value pair. Note: if multiple handlers are used, same secret name and different secret value for the same url won't work. Example:
	// A set of sensitive values that will be injected in the request (headers and/or payload), comprise of key/value pair.
	// +mapType=granular
	Secrets map[string]*string `json:"secrets,omitempty" tf:"secrets,omitempty"`

	// Specifies the URL that the Webhook invokes. This will be the URL that Artifactory will send an HTTP POST request to.
	// Specifies the URL that the Webhook invokes. This will be the URL that Artifactory will send an HTTP POST request to.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type HandlerObservation struct {

	// HTTP headers you wish to use to invoke the Webhook, comprise key/value pair.
	// HTTP headers you wish to use to invoke the Webhook, comprise of key/value pair. Used in custom webhooks.
	// +mapType=granular
	HTTPHeaders map[string]*string `json:"httpHeaders,omitempty" tf:"http_headers,omitempty"`

	// This attribute is used to build the request body. Used in custom webhooks
	Payload *string `json:"payload,omitempty" tf:"payload,omitempty"`

	// Proxy key from Artifactory UI (Administration -> Proxies -> Configuration).
	// Proxy key from Artifactory UI (Administration -> Proxies -> Configuration)
	Proxy *string `json:"proxy,omitempty" tf:"proxy,omitempty"`

	// Defines a set of sensitive values (such as, tokens and passwords) that can be injected in the headers and/or payload.Secrets’ values are encrypted. In the header/payload, the value can be invoked using the {{.secrets.token}} format, where token is the name provided for the secret value. Comprise key/value pair. Note: if multiple handlers are used, same secret name and different secret value for the same url won't work. Example:
	// A set of sensitive values that will be injected in the request (headers and/or payload), comprise of key/value pair.
	// +mapType=granular
	Secrets map[string]*string `json:"secrets,omitempty" tf:"secrets,omitempty"`

	// Specifies the URL that the Webhook invokes. This will be the URL that Artifactory will send an HTTP POST request to.
	// Specifies the URL that the Webhook invokes. This will be the URL that Artifactory will send an HTTP POST request to.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type HandlerParameters struct {

	// HTTP headers you wish to use to invoke the Webhook, comprise key/value pair.
	// HTTP headers you wish to use to invoke the Webhook, comprise of key/value pair. Used in custom webhooks.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	HTTPHeaders map[string]*string `json:"httpHeaders,omitempty" tf:"http_headers,omitempty"`

	// This attribute is used to build the request body. Used in custom webhooks
	// +kubebuilder:validation:Optional
	Payload *string `json:"payload,omitempty" tf:"payload,omitempty"`

	// Proxy key from Artifactory UI (Administration -> Proxies -> Configuration).
	// Proxy key from Artifactory UI (Administration -> Proxies -> Configuration)
	// +kubebuilder:validation:Optional
	Proxy *string `json:"proxy,omitempty" tf:"proxy,omitempty"`

	// Defines a set of sensitive values (such as, tokens and passwords) that can be injected in the headers and/or payload.Secrets’ values are encrypted. In the header/payload, the value can be invoked using the {{.secrets.token}} format, where token is the name provided for the secret value. Comprise key/value pair. Note: if multiple handlers are used, same secret name and different secret value for the same url won't work. Example:
	// A set of sensitive values that will be injected in the request (headers and/or payload), comprise of key/value pair.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Secrets map[string]*string `json:"secrets,omitempty" tf:"secrets,omitempty"`

	// Specifies the URL that the Webhook invokes. This will be the URL that Artifactory will send an HTTP POST request to.
	// Specifies the URL that the Webhook invokes. This will be the URL that Artifactory will send an HTTP POST request to.
	// +kubebuilder:validation:Optional
	URL *string `json:"url" tf:"url,omitempty"`
}

// CustomWebhookSpec defines the desired state of CustomWebhook
type CustomWebhookSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CustomWebhookParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CustomWebhookInitParameters `json:"initProvider,omitempty"`
}

// CustomWebhookStatus defines the observed state of CustomWebhook.
type CustomWebhookStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CustomWebhookObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CustomWebhook is the Schema for the CustomWebhooks API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,artifactory}
type CustomWebhook struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.criteria) || (has(self.initProvider) && has(self.initProvider.criteria))",message="spec.forProvider.criteria is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.eventTypes) || (has(self.initProvider) && has(self.initProvider.eventTypes))",message="spec.forProvider.eventTypes is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.handler) || (has(self.initProvider) && has(self.initProvider.handler))",message="spec.forProvider.handler is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.key) || (has(self.initProvider) && has(self.initProvider.key))",message="spec.forProvider.key is a required parameter"
	Spec   CustomWebhookSpec   `json:"spec"`
	Status CustomWebhookStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CustomWebhookList contains a list of CustomWebhooks
type CustomWebhookList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CustomWebhook `json:"items"`
}

// Repository type metadata.
var (
	CustomWebhook_Kind             = "CustomWebhook"
	CustomWebhook_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CustomWebhook_Kind}.String()
	CustomWebhook_KindAPIVersion   = CustomWebhook_Kind + "." + CRDGroupVersion.String()
	CustomWebhook_GroupVersionKind = CRDGroupVersion.WithKind(CustomWebhook_Kind)
)

func init() {
	SchemeBuilder.Register(&CustomWebhook{}, &CustomWebhookList{})
}
