apiVersion: localalpinerepository.crossplane.io/v1alpha1
kind: AlpineRepository
metadata:
  annotations:
    meta.upbound.io/example-id: localalpinerepository/v1alpha1/alpinerepository
  labels:
    testing.upbound.io/example-name: terraform-local-test-alpine-repo-basic
  name: terraform-local-test-alpine-repo-basic
spec:
  forProvider:
    key: terraform-local-test-alpine-repo-basic
    primaryKeypairRef: ${artifactory_keypair.some-keypairRSA.pair_name}

---

apiVersion: keypair.crossplane.io/v1alpha1
kind: Keypair
metadata:
  annotations:
    meta.upbound.io/example-id: localalpinerepository/v1alpha1/alpinerepository
  labels:
    testing.upbound.io/example-name: some-keypairRSA
  name: some-keypairrsa
spec:
  forProvider:
    alias: foo-alias
    pairName: some-keypair
    pairType: RSA
    privateKeySecretRef:
      key: attribute.rsa.priv
      name: example-secret
      namespace: upbound-system
    publicKey: ${file("samples/rsa.pub")}
