apiVersion: federatedcocoapodsrepository.crossplane.io/v1alpha1
kind: CocoapodsRepository
metadata:
  annotations:
    meta.upbound.io/example-id: federatedcocoapodsrepository/v1alpha1/cocoapodsrepository
  labels:
    testing.upbound.io/example-name: terraform-federated-test-cocoapods-repo
  name: terraform-federated-test-cocoapods-repo
spec:
  forProvider:
    key: terraform-federated-test-cocoapods-repo
    member:
      - enabled: true
        url: http://tempurl.org/artifactory/terraform-federated-test-cocoapods-repo
      - enabled: true
        url: http://tempurl2.org/artifactory/terraform-federated-test-cocoapods-repo-2
