apiVersion: virtualmavenrepository.crossplane.io/v1alpha1
kind: MavenRepository
metadata:
  annotations:
    meta.upbound.io/example-id: virtualmavenrepository/v1alpha1/mavenrepository
  labels:
    testing.upbound.io/example-name: maven-virt-repo
  name: maven-virt-repo
spec:
  forProvider:
    description: A test virtual repo
    excludesPattern: com/google/**
    forceMavenAuthentication: true
    includesPattern: com/jfrog/**,cloud/jfrog/**
    key: maven-virt-repo
    notes: Internal description
    pomRepositoryReferencesCleanupPolicy: discard_active_reference
    repoLayoutRef: maven-2-default
    repositories:
    - ${artifactory_local_maven_repository.bar.key}
    - ${artifactory_remote_maven_repository.baz.key}

---

apiVersion: localmavenrepository.crossplane.io/v1alpha1
kind: MavenRepository
metadata:
  annotations:
    meta.upbound.io/example-id: virtualmavenrepository/v1alpha1/mavenrepository
  labels:
    testing.upbound.io/example-name: bar
  name: bar
spec:
  forProvider:
    key: bar
    repoLayoutRef: maven-2-default

---

apiVersion: remotemavenrepository.crossplane.io/v1alpha1
kind: MavenRepository
metadata:
  annotations:
    meta.upbound.io/example-id: virtualmavenrepository/v1alpha1/mavenrepository
  labels:
    testing.upbound.io/example-name: baz
  name: baz
spec:
  forProvider:
    key: baz
    repoLayoutRef: maven-2-default
    url: https://search.maven.com/
