apiVersion: virtual_alpine_repository.crossplane.io/v1alpha1
kind: AlpineRepository
metadata:
  annotations:
    meta.upbound.io/example-id: virtual_alpine_repository/v1alpha1/alpinerepository
  labels:
    testing.upbound.io/example-name: foo-alpine
  name: foo-alpine
spec:
  forProvider:
    description: A test virtual repo
    excludesPattern: com/google/**
    includesPattern: com/jfrog/**,cloud/jfrog/**
    key: foo-alpine
    notes: Internal description
    repositories: []
